name: Build, Test and Deploy Quarkus Backend

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build and Test Quarkus backend
      working-directory: ./back
      run: |
        ./mvnw test
        ./mvnw package -DskipTests=false

